name: CI

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run format check
        run: poetry run poe format_check
  
  unit-check:
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run unit tests
        run: poetry run poe unit_test

